// Stage 1 realtime-collab POC: expose prosemirror-sync APIs and prove that
// server-side collaborators can edit a document through the same step stream.
// The `components.prosemirrorSync` type is generated by `convex dev` after the
// component is registered in convex.config.ts.

import { ProsemirrorSync } from "@convex-dev/prosemirror-sync";
import { getHubbleEditorSchema } from "@hubble.md/editor";
import { Transform } from "@tiptap/pm/transform";
import { v } from "convex/values";
import { components } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { type MutationCtx, mutation, type QueryCtx } from "./_generated/server";
import {
	documentIdFromSyncId,
	requireDocumentRead,
	requireDocumentWrite,
} from "./permissions";

const prosemirrorSync = new ProsemirrorSync(components.prosemirrorSync);

async function checkRead(ctx: QueryCtx, syncId: string) {
	const documentId = documentIdFromSyncId(syncId);
	if (!documentId) return;
	await requireDocumentRead(ctx, documentId);
}

async function checkWrite(ctx: MutationCtx, syncId: string) {
	const documentId = documentIdFromSyncId(syncId);
	if (!documentId) return;
	await requireDocumentWrite(ctx, documentId);
}

// Realtime sync endpoints consumed by the Tiptap client via `useTiptapSync`.
export const {
	getSnapshot,
	submitSnapshot,
	latestVersion,
	getSteps,
	submitSteps,
} = prosemirrorSync.syncApi({
	checkRead,
	checkWrite,
});

// --- Agent edit path (Model C) -------------------------------------------
// Proves the decision-gate question "can an agent edit server-side, no browser?"
// `transform` receives the latest doc and returns a ProseMirror Transform/Transaction;
// the change streams to every connected human like any collaborator edit.
//
// The real Model C API (`applyPatch(id, baseRevision, intent)`, outline-targeted
// edits) is built on top of this in Stage 4. This is the minimal proof.
//
export const agentAppendParagraph = mutation({
	args: { docId: v.string(), text: v.string() },
	handler: async (ctx, { docId, text }) => {
		const liveDocumentId = documentIdFromSyncId(docId);
		if (liveDocumentId) await requireDocumentWrite(ctx, liveDocumentId);

		const schema = getHubbleEditorSchema();
		const paragraph = schema.nodes.paragraph;
		if (!paragraph) {
			throw new Error("Hubble editor schema is missing paragraph node");
		}

		await prosemirrorSync.transform(ctx, docId, schema, (doc) => {
			const tr = new Transform(doc);
			const paragraphNode = paragraph.create(
				null,
				text.length > 0 ? schema.text(text) : undefined,
			);
			tr.insert(doc.content.size, paragraphNode);
			return tr;
		});

		if (docId.startsWith("document:")) {
			await ctx.db.patch(docId.slice("document:".length) as Id<"documents">, {
				updatedBy: "Agent",
				updatedAt: Date.now(),
			});
		}
	},
});
