// Stage 1 realtime-collab POC: expose prosemirror-sync APIs and prove that
// server-side collaborators can edit a document through the same step stream.
// The `components.prosemirrorSync` type is generated by `convex dev` after the
// component is registered in convex.config.ts.

import { ProsemirrorSync } from "@convex-dev/prosemirror-sync";
import { components } from "./_generated/api";
import type { MutationCtx, QueryCtx } from "./_generated/server";
import {
	documentIdFromSyncId,
	requireDocumentRead,
	requireDocumentWrite,
} from "./permissions";

const prosemirrorSync = new ProsemirrorSync(components.prosemirrorSync);

function requireLiveDocumentSyncId(syncId: string) {
	const documentId = documentIdFromSyncId(syncId);
	if (!documentId) {
		throw new Error("Unauthorized");
	}
	return documentId;
}

async function checkRead(ctx: QueryCtx, syncId: string) {
	const documentId = requireLiveDocumentSyncId(syncId);
	await requireDocumentRead(ctx, documentId);
}

async function checkWrite(ctx: MutationCtx, syncId: string) {
	const documentId = requireLiveDocumentSyncId(syncId);
	await requireDocumentWrite(ctx, documentId);
}

// Realtime sync endpoints consumed by the Tiptap client via `useTiptapSync`.
export const {
	getSnapshot,
	submitSnapshot,
	latestVersion,
	getSteps,
	submitSteps,
} = prosemirrorSync.syncApi({
	checkRead,
	checkWrite,
});
